### ISSUE TITLE
Nicer architecture

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/android_packages_apps_PowerOff#2]
1) Don't use two methods "reboot()" and "shutdown()" doing basically the same thing. Extract one new method "execCommand(String cmd)" and pass the specific command for reboot or shutdown to this method.

2) Terminate the application in any case (not only on failure) by calling "finish()".

**Comment by luetzenkirchen** [comment]
Done. View push on 12:50, 05.10.16
