### ISSUE TITLE
Nicer (and bigger) icons

### ISSUE THREAD

**Issue by ikalkov** [RTAndroid/android_packages_apps_PowerOff#4]
We should replace own-made icons by a set of nice looking icons. The current one looks poor on big resolutions:

![low_resolution](https://cloud.githubusercontent.com/assets/1721486/19083096/2359006e-8a61-11e6-962f-40a398f36806.png)

For this, we should download several different sizes for reboot and shutdown, put them in folders for different resolutions (hdpi, mdpi, xhdpi, ...) and let Android choose the correct one at runtime. Example for "shutdown": https://icons8.com/web-app/for/androidL/shutdown

Additionally, we should copy and modify one of those to make a better noticeable launcher icon out of it (e.g. make it red).

**Comment by luetzenkirchen** [comment]
Done. View branch from 11:49, 05.10.2016
